[workspace]
resolver = "2"
members = [
    "claims",
    "enclave-bridge",
    "teerex",
    "parentchain",
    "sidechain",
    "teerex/sgx-verify",
    "teeracle",
    "test-utils",
    "xcm-transactor",
    "primitives/claims",
    "primitives/enclave-bridge",
    "primitives/teerex",
    "primitives/teeracle",
    "primitives/common",
    "primitives/xcm-transactor",
]

[workspace.dependencies]
base64 = { version = "0.13", default-features = false, features = ["alloc"] }
chrono = { version = "0.4", default-features = false, features = ["serde"] }
derive_more = "0.99.16"
env_logger = "0.9.0"
hex = { default-features = false, version = "0.4.3", features = ["alloc"] }
hex-literal = "0.3.3"
log = { version = "0.4.20", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
serde = { version = "1.0.188", default-features = false, features = ["alloc", "derive"] }
serde_derive = { version = "1.0.188" }
serde_json = { version = "1.0", default-features = false }

# crypto [no_std]
der = { version = "0.6.0", default-features = false }
libsecp256k1 = { version = "0.7.0", default-features = false }
ring = { version = "0.16.20", default-features = false, features = ["alloc"] }
webpki = { git = "https://github.com/rustls/webpki", version = "=0.102.0-alpha.3", rev = "da923ed", package = "rustls-webpki", default-features = false, features = ["alloc", "ring"] }
x509-cert = { default-features = false, version = "0.1.0", features = ["alloc"] }

# polkadot-sdk and ecosystem crates [no_std]
cumulus-primitives-core = { version = "0.4.0", default-features = false }
frame-benchmarking = { version = "25.0.0", default-features = false }
frame-support = { version = "25.0.0", default-features = false }
frame-system = { version = "25.0.0", default-features = false }
pallet-balances = { version = "25.0.0", default-features = false }
pallet-timestamp = { version = "24.0.0", default-features = false }
pallet-vesting = { version = "25.0.0", default-features = false }
parity-scale-codec = { version = "3.6.4", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive", "serde"] }
sp-core = { version = "25.0.0", default-features = false }
sp-io = { version = "27.0.0", default-features = false }
sp-runtime = { version = "28.0.0", default-features = false }
sp-std = { version = "12.0.0", default-features = false }
substrate-fixed = { version = "0.5.9", default-features = false }
staging-xcm = { version = "4.0.0", default-features = false }

# dev-deps [std]
sp-keyring = { version = "28.0.0", default-features = false }
sp-externalities = { version = "0.23.0", default-features = false }
