[workspace]
members = [
    "claims",
    "teerex",
    "parentchain",
    "sidechain",
    "teerex/ias-verify",
    "teeracle",
    "test-utils",
    "xcm-transactor",
    "primitives/claims",
    "primitives/teerex",
    "primitives/teeracle",
    "primitives/common",
    "primitives/xcm-transactor",
]
