[workspace]
members = [
    "claims",
    "teerex",
    "parentchain",
    "sidechain",
    "teerex/sgx-verify",
    "teeracle",
    "test-utils",
    "primitives/claims",
    "primitives/teerex",
    "primitives/teeracle",
    "primitives/common",
]
